### PR TITLE
feat: AI capabilities expansion — LLM, extraction, guardrails, OCR, vision, agents

### PR DESCRIPTION
**Pull request by davidnich**
## Summary

Comprehensive AI capabilities expansion for the Qore runtime, implementing all 6 capabilities from the AI expansion plan:

### New Qore Modules (8)
- **QoreLlmUtils** — Pluggable LLM backend (HTTP/OpenAI, Anthropic, callback) with multi-turn chat, tool calling, SSE streaming, retry with backoff, image content blocks
- **QoreStructuredExtraction** — Schema-enforced data extraction from text/images with validation, retry, confidence scoring, few-shot examples
- **QoreGuardrails** — Content safety: PII detection (international, Luhn/IBAN validation), prompt injection (weighted confidence), toxicity, hallucination, topic restriction, output format enforcement. Direction filtering (input/output), fail-closed mode
- **QoreOcrUtils** — Universal document OCR: native Tesseract + HTTP, PDF page extraction, multi-page TIFF, format auto-detection, ImageMagick conversion
- **QoreVisionExtraction** — Multimodal LLM vision: image description, table extraction, text extraction, structured extraction. Built on LlmBackend
- **QoreAgentStrategies** — Configurable agent execution: SimpleAgentStrategy (tool-calling loop), PlanningAgentStrategy, ReflexionAgentStrategy, ParallelToolDispatcher. Event callbacks for observability

### New C++ Binary Module
- **modules/ocr** — Tesseract OCR engine (TesseractEngine class, extractText/extractTextWithMetadata, block-level bounding boxes, conditional build)

### C++ Module Enhancements
- **modules/ml** — New vector math functions: `ml_l2_normalize`, `ml_mean_pool`, `ml_max_pool`, `ml_cosine_similarity_batch` (Eigen SIMD accelerated)
- **modules/tokenizer** — Batch decode, special token accessors (EOS/BOS/CLS/SEP/UNK), `tokenizer_config.json` loading, chat template engine, Split/Punctuation/Digits pre-tokenizers (replacing stubs)

### DataProviderML Processors (12 new)
- extract-structured, rerank-text, semantic-chunk-text, guardrail-filter, guardrail-transform, ocr, pdf-ocr, document-ocr, vision-extraction

### Cross-Cutting Improvements
- All HTTP modules migrated from RestClient to **RestClientIo** (HTTP/2+3 multiplexing, auto-JSON)
- Qorus-specific `"qorus"` mode replaced with generic **`"callback"` mode** — zero Qorus dependencies
- Abbreviation-aware sentence splitting, configurable embedding pooling (mean/cls/max), IBAN country-length validation, cross-encoder activation config, endpoint format config
- EmbeddingModel/SemanticDocumentChunker use C++ `ml_mean_pool`/`ml_l2_normalize`/`ml_cosine_similarity` instead of Qore loops
- `%requires ml` (hard dependency, not try-module) — ml is always present
- All `NoRestClient`/`NoStreaming` guards removed — these modules are always present

## Test plan

- [x] All new test suites pass (QoreLlmUtils, QoreStructuredExtraction, QoreGuardrails, QoreOcrUtils, QoreVisionExtraction, QoreAgentStrategies, QoreTokenizerUtils)
- [x] All existing test suites pass (DataProviderML 94 tests, ml 288 tests, tokenizer 22 tests)
- [x] OCR module: valgrind clean on C++ tests with real image OCR
- [x] ml module: valgrind clean on new vector math functions
- [x] tokenizer module: valgrind clean on new methods
- [x] CI pipeline green

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: examples/test/qlib/QoreVisionExtraction/QoreVisionExtraction.qtest [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+%exec-class QoreVisionExtractionTest
+
+public class QoreVisionExtractionTest inherits QUnit::Test {
+    constructor() : Test("QoreVisionExtractionTest", "1.0") {
+        # Config validation tests
+        addTestCase("VisionLlmClient - invalid mode", \visionInvalidModeTest());
+        addTestCase("VisionLlmClient - valid http config", \visionValidHttpTest());
+        addTestCase("VisionLlmClient - valid anthropic config", \visionValidAnthropicTest());
+        addTestCase("VisionLlmClient - openai backward compat", \visionOpenaiCompatTest());
+        addTestCase("VisionLlmClient - qorus mode", \visionQorusModeTest());
```
[the remark this answers is not in the document]
Comment (davidnich) [reply examples/test/qlib/QoreVisionExtraction/QoreVisionExtraction.qtest]: Fixed in d00a64b — renamed test case and method to "callback mode".

File: modules/ml/src/ql_ml.qpp [hunk 2]
```diff
@@ -2231,4 +2231,238 @@ float ml_manhattan_distance(list<auto> a, list<auto> b) [dom=DEFAULT] {
...
+    if (norm > 0.0) {
+        vec /= norm;
+    }
+    return eigenVectorToQoreList(vec);
+}
+
+//! Mean-pools a matrix of token embeddings weighted by an attention mask
+/** Computes the weighted average of rows (token embeddings) where the weight
+    for each row is the corresponding attention mask value.  This is the
+    standard pooling operation for sentence embeddings from transformer models.
```
[the remark this answers is not in the document]
Comment (davidnich) [reply modules/ml/src/ql_ml.qpp]: Fixed in d00a64b — updated docstring to clarify the mask is binary (0/1 inclusion), not a weighted average.

File: modules/ml/src/ql_ml.qpp [hunk 3]
```diff
@@ -2231,4 +2231,238 @@ float ml_manhattan_distance(list<auto> a, list<auto> b) [dom=DEFAULT] {
...
+            "embeddings must be a list of lists");
+        return QoreValue();
+    }
+    size_t dim = first_list->size();
+    VectorXd sum = VectorXd::Zero(dim);
+    double mask_sum = 0.0;
+
+    for (size_t i = 0; i < embeddings->size(); ++i) {
+        int m = (int)mask->retrieveEntry(i).getAsBigInt();
+        if (m) {
```
[the remark this answers is not in the document]
Comment (davidnich) [reply modules/ml/src/ql_ml.qpp:2317]: Addressed above.

File: modules/ml/src/ql_ml.qpp [hunk 4]
```diff
@@ -2231,4 +2231,238 @@ float ml_manhattan_distance(list<auto> a, list<auto> b) [dom=DEFAULT] {
...
+            if ((size_t)row.size() != dim) {
+                xsink->raiseException("ML-VECTOR-ERROR",
+                    "all embeddings must have the same dimension: expected %d, got %d at index %d",
+                    (int)dim, (int)row.size(), (int)i);
+                return QoreValue();
+            }
+            sum += row;
+            mask_sum += 1.0;
+        }
+    }
```
[the remark this answers is not in the document]
Comment (davidnich) [reply modules/ml/src/ql_ml.qpp:2330]: Addressed above.

File: lib/thread.cpp [hunk 5]
```diff
@@ -3353,6 +3353,42 @@ QoreNamespace* get_thread_ns(QoreNamespace &qorens) {
...
 
+void ThreadProgramData::clearAllProgramThreadData(ExceptionSink* xsink) {
+    AutoLocker al(pslock);
+    for (auto& i : pgm_set) {
+        qore_program_private::clearThreadData(*i, xsink);
+    }
+}
+
+void clear_all_program_thread_local_data() {
+    ThreadData* td = thread_data.get();
```
[the remark this answers is not in the document]
Comment (davidnich) [reply lib/thread.cpp:3364]: Fixed in d00a64b — added early return when td is null.

File: lib/QC_ThreadPool.qpp [hunk 6]
```diff
@@ -64,6 +64,10 @@ void ThreadPoolThread::worker(ExceptionSink* xsink) {
         // next ThreadTask::run() sees *xsink == true in the program-context check
         // and silently skips execution.
         xsink->handleExceptions();
+        // Clear all thread-local data (program tld hash + thread_local vars + thread
+        // resources) to prevent data from leaking between unrelated tasks on the same
+        // worker thread.
+        clear_all_program_thread_local_data();
         sl.lock();
         task->del(xsink);
         task = 0;
```
[the remark this answers is not in the document]
Comment (davidnich) [reply lib/QC_ThreadPool.qpp]: Fixed in 8f72257 — moved clear_all_program_thread_local_data() after task->del(xsink) so destructors still have access to thread-local state, matching the AsyncIoController ordering.

File: CMakeLists.txt [hunk 7]
```diff
@@ -957,6 +957,7 @@ set(LIBQORE_CPP_SRC
     lib/QoreSandboxManager.cpp
     lib/DateTime.cpp
     lib/QoreLib.cpp
+    lib/qore_git_revision.cpp
```
[the remark this answers is not in the document]
Comment (davidnich) [reply CMakeLists.txt:960]: No duplicate symbol issue here. In SCU mode, `add_library` uses `single-compilation-unit.cpp + LIBQORE_EXTRA_SRC` — `LIBQORE_CPP_SRC` is never referenced. In non-SCU mode, `add_library` uses `LIBQORE_CPP_SRC` — `LIBQORE_EXTRA_SRC` is never set. The SCU is hardcoded `#include` lines, not generated from `LIBQORE_CPP_SRC`, and `qore_git_revision.cpp` is not in the SCU includes. The file is compiled exactly once in each mode.

File: CMakeLists.txt [hunk 8]
```diff
@@ -1603,10 +1604,12 @@ if (SINGLE_COMPILATION_UNIT)
         file(APPEND ${CMAKE_CURRENT_BINARY_DIR}/lib/single-compilation-unit.cpp
             "#include \"${CMAKE_BINARY_DIR}/ql_alloc_tracking.cpp\"\n")
     endif ()
-    # AllocTracking.cpp defines global malloc/free symbols and must be compiled separately from the SCU
-    set(LIBQORE_EXTRA_SRC "")
+    # Files that must be compiled separately from the SCU:
+    # - qore_git_revision.cpp: so git hash changes only recompile this tiny file
+    # - AllocTracking.cpp: defines global malloc/free symbols
```
[the remark this answers is not in the document]
Comment (davidnich) [reply CMakeLists.txt:1609]: Addressed above — no duplicate, each mode only compiles the file once.
